{
 "title": "TESTING Explain Analyze Logs",
 "time": { "from": "now-72h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "query_name",
    "query": {}
   },
   {
    "name": "database",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Information",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Important!\n\n## Please note that this dashboard is for testing only.\n\n## [Check this link for production dashboard](http://localhost:3000/a/ivarehaugland-explaindbdashboard-app/home)\n"
   }
  },
  {
   "title": "All Queries",
   "type": "table",
   "description": "Includes table with important fields for all queries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"vector\"} |= `explain_logger` |= `db_name` != `level_divide`"
    }
   ]
  },
  {
   "title": "Nodes for $query_name",
   "type": "table",
   "description": "Includes table with important fields for all queries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"vector\"} |= `graph_node_logger` != `source` or `target` or `mainstat` |= `$query_name`"
    }
   ]
  },
  {
   "title": "All Databases",
   "type": "table",
   "description": "Includes table with important fields for all queries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"vector\"} |= `db_logger` |= `db_name` != `level_divide`"
    }
   ]
  },
  {
   "title": "Query Statement",
   "type": "logs",
   "description": "Includes table with important fields for all queries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"vector\"} |= `explain_logger` |= `$query_name` |= `$database` != `level_divide` | json | line_format `{{.message_sql}}`"
    }
   ]
  },
  {
   "title": "Execution Plan Graph",
   "type": "nodeGraph",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"vector\"} |= `graph_node_logger` |= `$query_name` |= `$database` |= `mainstat`"
    },
    {
     "direction": "backward",
     "expr": "{job=\"vector\"} |= `graph_node_logger` |= `$query_name` |=`$database` |= `source`"
    }
   ]
  },
  {
   "title": "Execution Order Trees",
   "type": "pgillich-tree-panel",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"vector\"} |= `explain_logger` |= `level_divide`"
    }
   ]
  },
  {
   "title": "Total Execution Times",
   "type": "gauge",
   "gridPos": { "h": 31, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"vector\"} |= `explain_logger` != `level_divide` |= `total_exc_time` | json | keep message_total_exc_time, message_query_name | line_format `{{.message_total_exc_time}} {{.message_query_name}}`"
    }
   ]
  },
  {
   "title": "Plan Raw",
   "type": "logs",
   "gridPos": { "h": 27, "w": 24, "x": 0, "y": 107 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"vector\"} |= `\"source_type\":\"explain_file_json\"` |= `$query_name` | json"
    }
   ]
  }
 ]
}