services:
  proxy:
    container_name: dol-proxy
    image: traefik:v3.0
    networks:
      - external-network  # Connect to app network
    volumes:
      - ${OPTIONAL_DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
    ports:
      - "80:80"
      - "8090:8080"
    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `external-network`)
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --accesslog
      - --log
      - --log.level=DEBUG
      - --api
      - --api.insecure=true
    labels:
      - traefik.enable=true
      - traefik.constraint-label=external-network

  db-optimize-logger:
    container_name: dol
    image: dol
    env_file:
      - .env
    environment:
      - LOKI_CONFIG_HOST_PATH=${PWD}/loki.yaml
    build:
      context: ./db-optimize-logger
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    networks:
      - external-network
    volumes:
      - ./file/explain_output:/app/file/explain_output
      - ./file/graphs_output:/app/file/graphs_output
      - ${OPTIONAL_DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.docker.network=external-network
      - traefik.constraint-label=external-network
      - traefik.http.services.dol.loadbalancer.server.port=8080
      - traefik.http.routers.dol-http.rule=Host(`dol.localhost`)
      - traefik.http.routers.dol-http.entrypoints=http
      - traefik.http.routers.dol-https.rule=Host(`dol.localhost`)
      - traefik.http.routers.dol-https.entrypoints=https
      - traefik.http.routers.dol-https.tls=true

  vector:
    container_name: dol-vector
    image: timberio/vector:0.46.1-debian
    restart: "no"
    ports:
      - "8686:8686"
    env_file:
      - .env
    networks:
     - external-network
    volumes:
      - ./file:/var/log/
      - ./vector/vector.yaml:/etc/vector/vector.yaml:ro
      - ./vector/transformers:/etc/vector/transformers:ro
      - ${OPTIONAL_DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock

  grafana:
    extends:
      file: ./ivarehaugland-explaindbdashboard-app/.config/docker-compose-base.yaml
      service: grafana
    networks:
      - external-network

volumes:
  dolgrafana-data:
    name: "dol-grafana-data"
  dol-loki-data:
    name: "dol-loki-data"

networks:
  external-network:
    external: true
    name: ${NETWORK?Variable not set}
