{
 "title": "Explain Analyze Logs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "query_id",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "direction": "backward" }
   ]
  },
  {
   "title": "Explain Texts",
   "type": "logs",
   "gridPos": { "h": 15, "w": 19, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"vector\"} |= `\"logger\":\"explain_analyze_text\"` | json | line_format ` {{ .message_query_id }} {{ .message_explain_text }}`"
    }
   ]
  },
  {
   "title": "Actual Total&Execution Time table",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"vector\"} |= `explain_file_json`"
    }
   ]
  },
  {
   "title": "Line-Time metrics",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"vector\"} |= `explain_file_json` |= `$query_id`"
    }
   ]
  }
 ]
}